# Generated by Django 4.1.4 on 2022-12-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('residential_address', models.CharField(max_length=100)),
                ('registration_address', models.CharField(max_length=100)),
                ('personal_account', models.CharField(max_length=28)),
                ('premium', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeesShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
            options={
                'verbose_name': 'employee_shift',
                'verbose_name_plural': 'employees_shifts',
                'db_table': 'employees_shifts',
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='WorkingShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('hours_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'working_shift',
                'verbose_name_plural': 'working_shifts',
                'db_table': 'working_shifts',
            },
        ),
        migrations.CreateModel(
            name='WorkTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeesshifts')),
            ],
            options={
                'verbose_name': 'work_time_tracking',
                'verbose_name_plural': 'work_time_tracking',
                'db_table': 'work_time_tracking',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_qualification_level', models.IntegerField()),
                ('max_ql_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('year_experience_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('premium_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
            ],
            options={
                'db_table': 'specialities',
            },
        ),
        migrations.AddField(
            model_name='employeesshifts',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workingshifts'),
        ),
        migrations.AddField(
            model_name='employees',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialities'),
        ),
    ]
