# Generated by Django 4.1.4 on 2022-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimetracking',
            name='hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
